WebApp/WebApp/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using WebApp.Model;
using Microsoft.Extensions.Configuration;
using Microsoft.AspNetCore.Http;
using System.Net.Http;
using Newtonsoft.Json;
using System.Text;
using System.Net;
using DataTransfer;

namespace WebApp.Controllers
{
    public class HomeController : Controller
    {
        private readonly IConfigurationRoot Config;

        public HomeController(IConfigurationRoot config)
        {
            Config = config ?? throw new ArgumentNullException(nameof(config));
        }
        public IActionResult Index()
        {
            return View();
        }

        [HttpGet]
        public IActionResult Login()
        {

            return View(new LoginViewModel());
        }


        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Login(LoginViewModel model)
        {
            if (model != null && ModelState.IsValid)
            {
                var client = new HttpClient();
                StringContent content = new StringContent(JsonConvert.SerializeObject(model), Encoding.UTF8, "application/json");
                var result = await client.PostAsync(new Uri(Config["Api:Base"] + Config["Api:Login"]), content);
                
                if (!result.IsSuccessStatusCode) ModelState.AddModelError(string.Empty, "Could not authenticate.");
                else
                {
                    var token = JsonConvert.DeserializeObject<TokenDto>(await result.Content.ReadAsStringAsync());
                    CookieOptions options = new CookieOptions() { HttpOnly = true, Expires = token.Expiration };
                    Response.Cookies.Append(Config["Cookie:Token"], token.Value, options);
                    return RedirectToAction(nameof(Index));
                }
            }
            return View(model);
        }

        [HttpGet]
        public IActionResult Logout()
        {
            HttpContext.Response.Cookies.Delete(Config["Cookie:Token"]);
            return RedirectToAction(nameof(Index));
        }

        public IActionResult Error()
        {
            return View();
        }
    }
}

WebApp/WebApp/Controllers/RegionsController.cs
using AutoMapper;
using DataTransfer;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Configuration;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using WebApp.Model.Regions;
using WebAppDataLayer.Repository;

namespace WebApp.Controllers
{
    public class RegionsController : Controller
    {
        private readonly IRegionRepository RegionRepository;
        private readonly IMapper _mapper;
        private readonly IVisitorRepository _visitorRepository;

        public RegionsController(IRegionRepository regionRepository, IMapper mapper, IVisitorRepository visitorRepository)
        {
            RegionRepository = regionRepository ?? throw new ArgumentNullException(nameof(regionRepository));
            _mapper = mapper ?? throw new ArgumentNullException(nameof(mapper));
            _visitorRepository = visitorRepository ?? throw new ArgumentNullException(nameof(visitorRepository));
        }

        [HttpGet]
        public async Task<IActionResult> Index()
        {
            var regions = await RegionRepository.GetAllAsync();
            return View(regions);
        }

        [HttpGet]
        public async Task<IActionResult> Display(int id)
        {
            RegionDto region = await RegionRepository.GetAsync(id);
            DisplayRegionModel model = _mapper.Map<DisplayRegionModel>(region);
            if (region.VisitorIds != null)
            {
                List<VisitorDto> visitors = new List<VisitorDto>();
                foreach (var visitorId in region.VisitorIds)
                {
                    visitors.Add(await _visitorRepository.GetAsync(visitorId));
                }
                model.Visitors = visitors;
            }
            return View(model);
        }

        [HttpGet]
        public async Task<IActionResult> Delete(int id)
        {
            await RegionRepository.DeleteAsync(id);
            return RedirectToAction(nameof(Index));
        }

        [HttpGet]
        public async Task<IActionResult> RemoveVisitor(int regionId, int visitorId)
        {
            await RegionRepository.RemoveVisitorAsync(regionId, visitorId);
            return RedirectToAction(nameof(Display), new { id = regionId });
        }

        [HttpGet]
        public IActionResult Add()
        {
            return View(new RegionDto());
        }

        [HttpPost]
        public async Task<IActionResult> Add(AddRegionModel model)
        {
            if (ModelState.IsValid)
            {
                var region = await RegionRepository.AddAsync(_mapper.Map<RegionDto>(model));
                return RedirectToAction(nameof(Display), new { id = region.Id });
            }

            return View(model);
        }

        [HttpGet]
        public async Task<IActionResult> Update(int id)
        {
            RegionDto dto = await RegionRepository.GetAsync(id);
            return View(dto);
        }

        [HttpPost]
        public async Task<IActionResult> Update(RegionDto dto)
        {
            if (ModelState.IsValid)
            {
                await RegionRepository.UpdateAsync(dto);
                return RedirectToAction(nameof(Display), new { id = dto.Id });
            }

            return View(dto);
        }
    }
}

WebApp/WebApp/Controllers/VisitorsController.cs
using AutoMapper;
using DataTransfer;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net;
using System.Text;
using System.Threading.Tasks;
using WebApp.Model.Visitors;
using WebAppDataLayer.Repository;
using WebAppDataLayer.Repository.ApiRepository.ApiRepositoryExceptions;

namespace WebApp.Controllers
{
    public class VisitorsController : Controller
    {
        private readonly IVisitorRepository _visitorRepository;
        private IMapper _mapper;

        public VisitorsController(IVisitorRepository visitorRepository, IMapper mapper)
        {
            _visitorRepository = visitorRepository ?? throw new ArgumentNullException(nameof(visitorRepository));
            _mapper = mapper ?? throw new ArgumentNullException(nameof(mapper));
        }

        [HttpGet]
        public async Task<IActionResult> Index()
        {
            var visitors = await _visitorRepository.GetAllAsync();
            return View(visitors);
        }

        [HttpGet]
        public async Task<IActionResult> Display(int id)
        {
            VisitorDto visitor = await _visitorRepository.GetAsync(id);
            return View(visitor);
        }

        [HttpGet]
        public async Task<IActionResult> Delete(int id)
        {
            await _visitorRepository.DeleteAsync(id);
            return RedirectToAction(nameof(Index));
        }

        [HttpGet]
        public async Task<IActionResult> Update(int id)
        {
            VisitorDto dto = await _visitorRepository.GetAsync(id);
            return View(Mapper.Map<UpdateVisitorModel>(dto));
        }

        [HttpPost]
        public async Task<IActionResult> Update(UpdateVisitorModel model)
        {
            if (ModelState.IsValid)
            {
                try
                {
                    VisitorDto dto = await _visitorRepository.GetAsync(model.Id);
                    await _visitorRepository.UpdateAsync(_mapper.Map(model,dto));
                    return RedirectToAction(nameof(Display), new { id = model.Id });
                }
                catch (UnexpectedServerResponse e)
                {
                    if(e.StatusCode == HttpStatusCode.BadRequest)
                    {
                        ModelState.AddModelError(string.Empty, "Invalid data.");
                    }
                    else
                    {
                        throw;
                    }
                }
                
            }

            return View(model);
        }
    }
}

WebApp/WebApp/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}
<h1>@ViewData["Title"]</h1>

WebApp/WebApp/Views/Home/Login.cshtml
@model WebApp.Model.LoginViewModel
@{
    ViewData["Title"] = "Login";
}
<h1>@ViewData["Title"]</h1>
<form method="post" asp-controller="Home" asp-action="Login">
    <fieldset>
        <legend>Login</legend>
        @Html.ValidationSummary()
        <div>
            @Html.LabelFor(x => x.Email)
            @Html.EditorFor(x => x.Email)
            @Html.ValidationMessageFor(x => x.Email)
        </div>
        <div>
            @Html.LabelFor(x => x.Password)
            @Html.PasswordFor(x => x.Password)
            @Html.ValidationMessageFor(x => x.Password)
        </div>
        <input type="submit" value="Login"/>
    </fieldset>
</form>

WebApp/WebApp/Views/Regions/Add.cshtml
@model WebApp.Model.Regions.AddRegionModel
@{
    ViewData["Title"] = "Add region";
}
<h1>@ViewData["Title"]</h1>
<form method="post" asp-controller="Regions" asp-action="Add">
    <fieldset>
        <legend>Add region</legend>
        @Html.ValidationSummary()
        <div>
            @Html.LabelFor(x => x.Name)
            @Html.EditorFor(x => x.Name)
            @Html.ValidationMessageFor(x => x.Name)
        </div>
        <div>
            @Html.LabelFor(x => x.Description)
            @Html.EditorFor(x => x.Description)
            @Html.ValidationMessageFor(x => x.Description)
        </div>
        <div>
            @Html.LabelFor(x => x.Polygon)
            @Html.EditorFor(x => x.Polygon)
            @Html.ValidationMessageFor(x => x.Polygon)
        </div>
        <div>
            @Html.LabelFor(x => x.Value)
            @Html.EditorFor(x => x.Value)
            @Html.ValidationMessageFor(x => x.Value)
        </div>
        <div>
            @Html.LabelFor(x => x.TimeStamp)
            @Html.EditorFor(x => x.TimeStamp)
            @Html.ValidationMessageFor(x => x.TimeStamp)
        </div>
        <input type="submit" value="Add" />
    </fieldset>
</form>

WebApp/WebApp/Views/Regions/Display.cshtml
@model WebApp.Model.Regions.DisplayRegionModel

@{
    ViewData["Title"] = Model.Name;
}
<h1>@ViewData["Title"]</h1>
<p>@Model.Description</p>
<p><a asp-controller="Regions" asp-action="Update" asp-route-id="@Model.Id">Update</a> <a asp-controller="Regions" asp-action="Delete" asp-route-id="@Model.Id">Delete</a></p>
@if (Model.Visitors != null && Model.Visitors.Count>0)
{
    <h2>Visitors</h2>
    foreach (var visitor in Model.Visitors)
    {
        <p>@visitor.Username</p>
        <p>@visitor.Email</p>
        <p>@visitor.Bio</p>
        <p><a asp-controller="Regions" asp-action="RemoveVisitor" asp-route-regionId="@Model.Id" asp-route-visitorId="@visitor.Id">Remove</a> </p>
        <hr />
    }
}

WebApp/WebApp/Views/Regions/Index.cshtml
@model IEnumerable<DataTransfer.RegionDto>

@{
    ViewData["Title"] = "Regions";
}
<h1>@ViewData["Title"]</h1>
<p><a asp-controller="Regions" asp-action="Add">Add</a></p>
@foreach (var region in Model)
{
    <div>
        <h2>@region.Name</h2>
        <p>@region.Description</p>
        <p>@region.VisitorIds.Count() visitors.</p>
        <p><a asp-controller="Regions" asp-action="Display" asp-route-id="@region.Id">Display</a> <a asp-controller="Regions" asp-action="Update" asp-route-id="@region.Id">Update</a> <a asp-controller="Regions" asp-action="Delete" asp-route-id="@region.Id">Delete</a></p>
        <hr />
    </div>
}

WebApp/WebApp/Views/Regions/Update.cshtml
@model DataTransfer.RegionDto
@{
    ViewData["Title"] = "Update region";
}
<h1>@ViewData["Title"]</h1>
<form method="post" asp-controller="Regions" asp-action="Update">
    <fieldset>
        <legend>Update region</legend>
        @Html.ValidationSummary()
        @Html.HiddenFor(x => x.Id)
        <div>
            @Html.LabelFor(x => x.Name)
            @Html.EditorFor(x => x.Name)
            @Html.ValidationMessageFor(x => x.Name)
        </div>
        <div>
            @Html.LabelFor(x => x.Description)
            @Html.EditorFor(x => x.Description)
            @Html.ValidationMessageFor(x => x.Description)
        </div>
        <div>
            @Html.LabelFor(x => x.Polygon)
            @Html.EditorFor(x => x.Polygon)
            @Html.ValidationMessageFor(x => x.Polygon)
        </div>
        <div>
            @Html.LabelFor(x => x.Value)
            @Html.EditorFor(x => x.Value)
            @Html.ValidationMessageFor(x => x.Value)
        </div>
        <div>
            @Html.LabelFor(x => x.TimeStamp)
            @Html.EditorFor(x => x.TimeStamp)
            @Html.ValidationMessageFor(x => x.TimeStamp)
        </div>
        <input type="submit" value="Update" />
    </fieldset>
</form>

WebApp/WebApp/Views/Shared/_Layout.cshtml
@inject Microsoft.Extensions.Configuration.IConfigurationRoot Config
@inject Microsoft.AspNetCore.Http.IHttpContextAccessor HttpContextAccessor
@{ 

}
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"]</title>

    <environment names="Development">

    </environment>
    <environment names="Staging,Production">

    </environment>
</head>
<body>
    <div>
        <nav>
            <a asp-controller="Home" asp-action="Index">Home</a>
            @if (HttpContextAccessor.HttpContext.Request.Cookies[Config["Cookie:Token"]] != null)
            {
                <a asp-controller="Regions" asp-action="Index">Regions</a>
                <a asp-controller="Visitors" asp-action="Index">Visitors</a>
                <a asp-controller="Home" asp-action="Logout">Logout</a>
            }
            else
            {
                <a asp-controller="Home" asp-action="Login">Login</a>
            }
            
        </nav>
        @RenderBody()
        <footer>
            <p>&copy; 2017 - WebApp</p>
        </footer>
    </div>

    <environment names="Development">
    </environment>
    <environment names="Staging,Production">
    </environment>

    @RenderSection("Scripts", required: false)
</body>
</html>

WebApp/WebApp/Views/Visitors/Display.cshtml
@model DataTransfer.VisitorDto

@{
    ViewData["Title"] = Model.Username;
}
<h1>@ViewData["Title"]</h1>
<p>@Model.Bio</p>
<p>@Model.Email</p>
<p>
    <a asp-controller="Visitors" asp-action="Update" asp-route-id="@Model.Id">Update</a>
    <a asp-controller="Visitors" asp-action="Delete" asp-route-id="@Model.Id">Delete</a>
</p>

WebApp/WebApp/Views/Visitors/Index.cshtml
@model IEnumerable<DataTransfer.VisitorDto>

@{
    ViewData["Title"] = "Regions";
}
<h1>@ViewData["Title"]</h1>
@foreach (var visitor in Model)
{
    <div>
        <h2>@visitor.Username</h2>
        <p>@visitor.Bio</p>
        <p>@visitor.RegionIds.Count() linked regions.</p>
        <p>
            <a asp-controller="Visitors" asp-action="Display" asp-route-id="@visitor.Id">Display</a>
            <a asp-controller="Visitors" asp-action="Update" asp-route-id="@visitor.Id">Update</a>
            <a asp-controller="Visitors" asp-action="Delete" asp-route-id="@visitor.Id">Delete</a></p>
        <hr />
    </div>
}

WebApp/WebApp/Views/Visitors/Update.cshtml
@model WebApp.Model.Visitors.UpdateVisitorModel
@{
    ViewData["Title"] = "Update "+Model.Username;
}
<h1>@ViewData["Title"]</h1>
<form method="post" asp-controller="Visitors" asp-action="Update">
    <fieldset>
        <legend>Update region</legend>
        @Html.ValidationSummary()
        @Html.HiddenFor(x => x.Id)
        <div>
            @Html.LabelFor(x => x.Username)
            @Html.EditorFor(x => x.Username)
            @Html.ValidationMessageFor(x => x.Username)
        </div>
        <div>
            @Html.LabelFor(x => x.Email)
            @Html.EditorFor(x => x.Email)
            @Html.ValidationMessageFor(x => x.Email)
        </div>
        <div>
            @Html.LabelFor(x => x.Bio)
            @Html.EditorFor(x => x.Bio)
            @Html.ValidationMessageFor(x => x.Bio)
        </div>
        <input type="submit" value="Update" />
    </fieldset>
</form>